#ifndef __FILEOPS_H__
#define __FILEOPS_H__

//NOTE: Keys must not exceed 15 characters in length
//https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/storage/nvs_flash.html
#define KEY_SETVIEW "setView"
#define KEY_ACESSPOINT_PASSWORD "appw"
#define KEY_BOARD "board"
#define KEY_CPUFREQU "Frequ"
#define KEY_EXTPWSW "expwsw"
#define KEY_RFM "RFM"
#define KEY_AWLIVE "awlive"
#define KEY_OSerial "oSerial"
#define KEY_OVario "oVario"
#define KEY_OFLARM "oFlarm"
#define KEY_OGPS "oGPS"
#define KEY_OFANET "oFanet"
#define KEY_PILOTNAME "PilotName"
#define KEY_myDevId "myDevId"
#define KEY_myDevIdType "myDevIdType"
#define KEY_customGPSConfig "customGPSConfig"
#define KEY_GPSBAUD "GPSBAud"
#define KEY_WIFI_MODE "WIFI_MODE"
#define KEY_WIFI_CONNECT "wificonnect"
#define KEY_WIFI_SSID "ssid"
#define KEY_WIFI_PW "password"
#define KEY_AIRCRAFTTYPE "type"
#define KEY_WIFI_AP_STOP "wifioff"
#define KEY_WIFI_STA_STOP "wifiapoff"
#define KEY_UDP_SERVER "UDPServerIP"
#define KEY_UDP_PORT "UDPSendPort"
#define KEY_OutputMode "output"
#define KEY_Mode "mode"
#define KEY_fntMode "fntMode"
#define KEY_fntPin "fntPin"
#define KEY_AUTOUPDATE "AUTOUPDATE"
#define KEY_GSLAT "gslat"
#define KEY_GSLON "gslon"
#define KEY_GSALT "gsalt"
#define KEY_GSGEOALT "gsGeoAlt"
#define KEY_GSSCR "gsScr"
#define KEY_GSPS "gsPs"
#define KEY_GsSrO "GsSrO"
#define KEY_GsSsO "GsSsO"
#define KEY_GSANEO "wdAnemo"
#define KEY_WDANEOADSGAIN "wdAdsGain"
#define KEY_WDANEOADSVDIVR1 "wdAdsVDivR1"
#define KEY_WDANEOADSVDIVR2 "wdAdsVDivR2"
#define KEY_WDANEOADSWSMINV "wdAdsWSpdMinV"
#define KEY_WDANEOADSWSMAXV "wdAdsWSpdMaxV"
#define KEY_WDANEOADSWDMINV "wdAdsWDirMinV"
#define KEY_WDANEOADSWDMAXV "wdAdsWDirMaxV"
#define KEY_WDANEOADSWSMINS "wdAdsWSpdMinSpd"
#define KEY_WDANEOADSWSMAXS "wdAdsWSpdMaxSpd"
#define KEY_WDANEOADSWDMIND "wdAdsWDirMinDir"
#define KEY_WDANEOADSWDMAXD "wdAdsWDirMaxDir"
#define KEY_BattMinPerc "MinBatPerc"
#define KEY_BATOFFS "BATOFFS"
#define KEY_restartBattPerc "restartBattPerc"
#define KEY_F2WuF0 "F2WuF0"
#define KEY_F2WuF1 "F2WuF1"
#define KEY_F2WuF2 "F2WuF2"
#define KEY_F2WuF3 "F2WuF3"
#define KEY_F2WuF4 "F2WuF4"
#define KEY_F2WuI0 "F2WuI0"
#define KEY_F2WuI1 "F2WuI1"
#define KEY_F2WuI2 "F2WuI2"
#define KEY_F2WuI3 "F2WuI3"
#define KEY_F2WuI4 "F2WuI4"
#define KEY_F2WuK0 "F2WuK0"
#define KEY_F2WuK1 "F2WuK1"
#define KEY_F2WuK2 "F2WuK2"
#define KEY_F2WuK3 "F2WuK3"
#define KEY_F2WuK4 "F2WuK4"
#define KEY_F2WiF0 "F2WiF0"
#define KEY_F2WiF1 "F2WiF1"
#define KEY_F2WiF2 "F2WiF2"
#define KEY_F2WiF3 "F2WiF3"
#define KEY_F2WiF4 "F2WiF4"
#define KEY_F2WiI0 "F2WiI0"
#define KEY_F2WiI1 "F2WiI1"
#define KEY_F2WiI2 "F2WiI2"
#define KEY_F2WiI3 "F2WiI3"
#define KEY_F2WiI4 "F2WiI4"
#define KEY_F2WiK0 "F2WiK0"
#define KEY_F2WiK1 "F2WiK1"
#define KEY_F2WiK2 "F2WiK2"
#define KEY_F2WiK3 "F2WiK3"
#define KEY_F2WiK4 "F2WiK4"
#define KEY_OGN_LIVE "ognlive"
#define KEY_SCREEN "gsScr"
#define KEY_Display "disp"
#define KEY_DispRot "dispRot"
#define KEY_TRACCAR_LIVE "traccar_live"
#define KEY_TRACCAR_SRV "traccarsrv"
#define KEY_vSinkTh "vSinkTh"
#define KEY_vClimbTh "vClimbTh"
#define KEY_vNClimbSens "vNClimbSens"
#define KEY_VarioVolume "vVol"
#define KEY_VBeepFlying "vBeepFly"
#define KEY_useMPU "useMPU"
#define KEY_vTOffs "vTOffs"
#define KEY_vSigmaP "vSigmaP"
#define KEY_vSigmaA "vSigmaA"
#define KEY_WsMode "WsMode"
#define KEY_FanetWeather "sFWD"
#define KEY_wdTempOffset "wdTempOffset"
#define KEY_wdWDirOffset "wdWDirOffset"
#define KEY_avgFanet "WFFNT"
#define KEY_FanetWDInt "WIFNT"
#define KEY_avgWU "WFWU"
#define KEY_WUIntervall "WIWU"
#define KEY_WUUlEnable "tWu2"
#define KEY_WUUlID "WUUlID"
#define KEY_WUUlKEY "WUUlKEY"
#define KEY_WIUlEnable "WIUlEnable"
#define KEY_WIUlID "WIUlID"
#define KEY_WIUlKEY "WIUlKEY"
#define KEY_GSMAPN "GSMAPN"
#define KEY_GSMUSER "GSMUSER"
#define KEY_GSMKEY "GSMKEY"
#define KEY_GSMMODE "GSMMODE"
#define KEY_GSMPREF "GSMPREF"
#define KEY_NBIOT "NBIOT"
#define KEY_CATM "CATM"
#define KEY_fuelSensor "fuelSensor"
#define KEY_MqttEn "MqttEn"
#define KEY_MqttServer "MqttServer"
#define KEY_MqttPort "MqttPort"
#define KEY_MqttPw "MqttPw"
//fastvario
#define KEY_axOffset "axOffset"
#define KEY_ayOffset  "ayOffset"
#define KEY_azOffset "azOffset"
#define KEY_gxOffset "gxOffset"
#define KEY_gyOffset "gyOffset"
#define KEY_gzOffset "gzOffset"
#define KEY_t0 "t[0]"
#define KEY_t1 "t[1]"
#define KEY_z0 "z[0]"
#define KEY_z1 "z[1]"

#include "main.h"

extern SettingsData setting;

void load_configFile(SettingsData* pSetting);
void write_configFile(SettingsData* pSetting);
void write_screenNumber();
void write_Volume();
void write_PilotName();
void write_AircraftType();
void write_AirMode();
void write_Mode();
void write_RFMode();
void write_OutputMode();
void write_LoraPower();
void write_fuelsensor();
void write_battOffset();
void write_battMinPerc();
void write_gpsBaud();
void write_wifiModeBits();
void write_CPUFrequency();
#endif